"""Tests for :mod:`pixieduster.mining`.

Everything runs offline: the only network-capable function (``mine_prs``) is
exercised either with ``gh`` removed from ``PATH`` or with the subprocess
helper monkeypatched.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from pixieduster import mining
from pixieduster.types import Sample

REPO_ROOT = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
# fixture: a throwaway repo with real prose and plenty of noise
# --------------------------------------------------------------------------

GOOD_BODY = """Rework the sampler so short commits stop drowning the README

I kept seeing the persona come out flat and it turned out the commit
stream was eating the whole budget. The fix is to give each source a
share of the budget rather than a raw cap, because the shape of a repo
varies wildly and a hard cap punishes the sources with fewer items.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_abc123
"""

SECOND_BODY = """Explain why the doc cleaner drops tables

Tables are data, not voice. Keeping them made the model imitate column
alignment instead of sentence rhythm, which is not what anyone wants
out of a writing sample, so they go in the bin with the badges.

Signed-off-by: Someone Else <someone@example.com>
"""

ROBOT_BODY = (
    "Add the certificate panel\n\n"
    "The web app had a certificate and the CLI did not, so this ports the\n"
    "double gold border over to a rich Panel and keeps the wording.\n\n"
    "\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)\n"
)

README = """# Sparklefish

[![build](https://img.shields.io/badge/build-passing-green)](https://ci.example.com)
[![coverage](https://img.shields.io/badge/cov-99%25-blue)](https://cov.example.com)

<p align="center">A tiny tool with an oversized opinion about whitespace.</p>

Sparklefish exists because I got tired of writing the same forty lines of
argument parsing in every script I threw together on a Sunday afternoon. It
does one thing, it does it without asking questions, and it gets out of the
way when you are done with it.

```python
SECRET_FENCE_CONTENT = "this must not survive cleaning"
```

| column | column |
|---|---|
| a | b |

See the [docs][docs-link] if you want the longer version of the story.

[docs-link]: https://example.com/docs
"""

CHANGELOG = "# Changelog\n\n## 1.0.0\n\n- Did a thing\n- Did another thing\n" * 6
LICENSE = "MIT License\n\nCopyright (c) 2026 Somebody\n\n" + ("Permission is hereby granted, free of charge, to any person obtaining a copy.\n" * 8)

DESIGN_DOC = """# Design notes

The whole design rests on one bet: that people write more honestly in commit
messages than they do in documentation, because nobody proofreads a commit.
If that bet is wrong the persona will read like a press release, and I would
rather find that out early than ship it and wonder.
"""

SOURCE_PY = '''#!/usr/bin/env python
"""Turn a pile of half-remembered arguments into a usable namespace.

This module is deliberately boring. Every clever thing I tried here made the
error messages worse, and error messages are the whole point of the exercise.
"""

import sys

TEMPLATE = """
## Core Directives
## Author Persona
"""


def parse(argv):
    """Parse ``argv`` and complain loudly when it makes no sense.

    The complaining is the feature. A parser that silently accepts nonsense
    just moves the confusion downstream to somebody with less context.
    """
    return argv  # noqa: E501


# The dispatch table below is ordered by how often each flag actually gets
# used, not alphabetically, because the alphabetical version made me scroll
# past the interesting cases every single time I opened this file.
TABLE = {}

x = 1  # trailing note that should never be captured on its own
'''

SOURCE_TS = """/*
 * The scheduler is intentionally single threaded. Every concurrency bug we
 * shipped last year came from two writers touching the same queue, and the
 * throughput win was never big enough to justify the pager going off.
 */
export function schedule(job: Job) {
  // Retry with a jittered backoff rather than a fixed one, because a fixed
  // delay turns a partial outage into a synchronised stampede the moment
  // everything comes back up at once.
  return job;
}
"""

GENERATED_PY = '''"""DO NOT EDIT. Code generated by the widget compiler.

This file contains a long and very human sounding docstring that should never
show up in the mined samples because the file announces itself as generated.
"""
'''

LICENSED_GO = """// Copyright 2026 The Sparklefish Authors. All rights reserved.
// Licensed under the Apache License, Version 2.0; you may not use this file
// except in compliance with the License. See the LICENSE file for details.

package main
"""


def _git(repo: Path, *args: str, **kw: object) -> None:
    subprocess.run(
        ["git", *args],
        cwd=str(repo),
        check=True,
        capture_output=True,
        timeout=30,
        env={
            "PATH": __import__("os").environ.get("PATH", ""),
            "HOME": str(repo),
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_AUTHOR_DATE": "2026-01-01T00:00:00+00:00",
            "GIT_COMMITTER_DATE": "2026-01-01T00:00:00+00:00",
            **{k: str(v) for k, v in kw.items()},
        },
    )


def _commit(repo: Path, message: str, *, name: str = "Gretchen Boria",
            email: str = "me@gretchenboria.com") -> None:
    _git(repo, "add", "-A")
    _git(
        repo, "-c", f"user.name={name}", "-c", f"user.email={email}",
        "commit", "--no-gpg-sign", "-m", message,
    )


@pytest.fixture(scope="module")
def repo(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A throwaway git repo containing real prose plus a lot of noise."""
    root = tmp_path_factory.mktemp("sparklefish")
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "commit.gpgsign", "false")

    (root / "README.md").write_text(README)
    (root / "CHANGELOG.md").write_text(CHANGELOG)
    (root / "LICENSE").write_text(LICENSE)
    (root / "LICENSE.txt").write_text(LICENSE)
    (root / "docs").mkdir()
    (root / "docs" / "design.md").write_text(DESIGN_DOC)
    (root / "src").mkdir()
    (root / "src" / "parser.py").write_text(SOURCE_PY)
    (root / "src" / "scheduler.ts").write_text(SOURCE_TS)
    (root / "src" / "widget_gen.py").write_text(GENERATED_PY)
    (root / "src" / "main.go").write_text(LICENSED_GO)
    (root / ".gitignore").write_text("ignored/\n")
    (root / "ignored").mkdir()
    (root / "ignored" / "secret_notes.md").write_text(
        "This gitignored file must never be mined. " * 20
    )
    _commit(root, GOOD_BODY)

    (root / "src" / "parser.py").write_text(SOURCE_PY + "\nY = 2\n")
    _commit(root, SECOND_BODY)

    (root / "src" / "parser.py").write_text(SOURCE_PY + "\nY = 3\n")
    _commit(root, ROBOT_BODY)

    # --- noise commits, none of which should survive ---
    noise = [
        ("chore(deps): bump lodash from 4.17.20 to 4.17.21\n\n"
         "Bumps lodash to the latest version with the prototype fix in it.\n",
         "Gretchen Boria", "me@gretchenboria.com"),
        ("Bump version to 2.0.1\n\nRoutine release bookkeeping for the tag.\n",
         "Gretchen Boria", "me@gretchenboria.com"),
        ("fix typo", "Gretchen Boria", "me@gretchenboria.com"),
        ("Update dependencies\n\nRegenerate the lock file after the audit run.\n",
         "dependabot[bot]", "support@github.com"),
        ("Add automated formatting\n\nRan prettier across the whole tree, no\n"
         "behaviour changes at all in this commit.\n",
         "renovate[bot]", "bot@renovateapp.com"),
    ]
    for i, (msg, name, email) in enumerate(noise):
        (root / f"noise{i}.txt").write_text("x")
        _commit(root, msg, name=name, email=email)

    # A merge commit, which --no-merges must exclude.
    _git(root, "checkout", "-q", "-b", "side")
    (root / "side.txt").write_text("side")
    _commit(root, "Side branch work that is long enough to survive min_chars easily")
    _git(root, "checkout", "-q", "main")
    _git(
        root, "-c", "user.name=Gretchen Boria", "-c", "user.email=me@gretchenboria.com",
        "merge", "--no-ff", "--no-gpg-sign", "-m",
        "Merge branch 'side' into main after a long and detailed discussion", "side",
    )
    return root


# --------------------------------------------------------------------------
# basics
# --------------------------------------------------------------------------


def test_is_git_repo(repo: Path, tmp_path: Path) -> None:
    assert mining.is_git_repo(repo) is True
    assert mining.is_git_repo(tmp_path) is False
    assert mining.is_git_repo(tmp_path / "does-not-exist") is False


def test_list_authors(repo: Path) -> None:
    authors = mining.list_authors(repo)
    emails = [e for e, _, _ in authors]
    assert "me@gretchenboria.com" in emails
    # sorted by commit count, descending
    counts = [c for _, _, c in authors]
    assert counts == sorted(counts, reverse=True)
    assert authors[0][0] == "me@gretchenboria.com"


# --------------------------------------------------------------------------
# commits
# --------------------------------------------------------------------------


def test_mine_commits_keeps_bodies_not_just_subjects(repo: Path) -> None:
    samples = mining.mine_commits(repo)
    assert samples
    assert all(s.kind == "commit" for s in samples)
    joined = "\n".join(s.text for s in samples)
    assert "share of the budget rather than a raw cap" in joined
    assert "Tables are data, not voice." in joined


def test_mine_commits_strips_trailers(repo: Path) -> None:
    joined = "\n".join(s.text for s in mining.mine_commits(repo))
    for forbidden in (
        "Co-Authored-By",
        "Claude-Session",
        "claude.ai/code",
        "noreply@anthropic.com",
        "\U0001F916",
        "Generated with [Claude Code]",
        "Signed-off-by",
    ):
        assert forbidden not in joined, f"trailer leaked: {forbidden}"
    # the human prose either side of the trailer survives
    assert "ports the" in joined


def test_mine_commits_filters_noise(repo: Path) -> None:
    joined = "\n".join(s.text for s in mining.mine_commits(repo)).lower()
    for forbidden in (
        "bumps lodash",
        "routine release bookkeeping",
        "fix typo",
        "regenerate the lock file",
        "ran prettier",
        "merge branch",
    ):
        assert forbidden not in joined, f"noise survived: {forbidden}"


def test_mine_commits_respects_min_chars_and_limit(repo: Path) -> None:
    assert all(len(s.text) >= 40 for s in mining.mine_commits(repo, min_chars=40))
    assert mining.mine_commits(repo, min_chars=100_000) == []
    assert len(mining.mine_commits(repo, limit=1)) == 1
    assert mining.mine_commits(repo, limit=0) == []


def test_mine_commits_author_filter(repo: Path) -> None:
    mine = mining.mine_commits(repo, author="me@gretchenboria.com")
    assert mine
    assert all(s.author == "me@gretchenboria.com" for s in mine)
    assert mining.mine_commits(repo, author="nobody@nowhere.invalid") == []


def test_mine_commits_origin_is_a_short_sha(repo: Path) -> None:
    for s in mining.mine_commits(repo):
        assert s.origin.startswith("git log ")
        assert len(s.origin.split()[-1]) == 7


def test_strip_trailers_keeps_prose_colons() -> None:
    body = "Fix the thing\n\nNote: this matters because of the ordering.\n\nSigned-off-by: A <a@b.c>\n"
    out = mining._strip_trailers(body)
    assert "Note: this matters" in out
    assert "Signed-off-by" not in out


# --------------------------------------------------------------------------
# docs
# --------------------------------------------------------------------------


def test_mine_docs_prefers_readme_and_skips_boilerplate(repo: Path) -> None:
    samples = mining.mine_docs(repo)
    origins = [s.origin for s in samples]
    assert origins[0] == "README.md"
    assert "docs/design.md" in origins
    assert not any("CHANGELOG" in o.upper() for o in origins)
    assert not any("LICENSE" in o.upper() for o in origins)
    assert all(s.kind == "doc" for s in samples)


def test_mine_docs_cleans_markup(repo: Path) -> None:
    readme = next(s for s in mining.mine_docs(repo) if s.origin == "README.md")
    assert "SECRET_FENCE_CONTENT" not in readme.text      # code fence
    assert "img.shields.io" not in readme.text            # badge line
    assert "example.com/docs" not in readme.text          # link reference block
    assert "<p align" not in readme.text                  # raw HTML
    assert "| column |" not in readme.text                # table row
    assert "oversized opinion about whitespace" in readme.text  # HTML inner text kept
    assert "Sunday afternoon" in readme.text
    assert "See the docs if you want" in readme.text      # link text kept, url dropped


def test_mine_docs_respects_gitignore(repo: Path) -> None:
    joined = "\n".join(s.text for s in mining.mine_docs(repo))
    assert "must never be mined" not in joined


def test_mine_docs_limit(repo: Path) -> None:
    assert len(mining.mine_docs(repo, limit=1)) == 1
    assert mining.mine_docs(repo, limit=0) == []


# --------------------------------------------------------------------------
# comments
# --------------------------------------------------------------------------


def test_mine_comments_extracts_docstrings_and_runs(repo: Path) -> None:
    samples = mining.mine_comments(repo)
    assert samples
    assert all(s.kind == "comment" for s in samples)
    joined = "\n".join(s.text for s in samples)
    assert "Every clever thing I tried here" in joined       # module docstring
    assert "The complaining is the feature." in joined       # function docstring
    assert "ordered by how often each flag" in joined        # multi-line # run
    assert "synchronised stampede" in joined                 # ts // run
    assert "single threaded" in joined                       # ts /* */ block


def test_mine_comments_filters_noise(repo: Path) -> None:
    joined = "\n".join(s.text for s in mining.mine_comments(repo))
    assert "noqa" not in joined                              # pragma
    assert "trailing note that should never" not in joined   # single trailing comment
    assert "widget compiler" not in joined                   # generated file
    assert "Apache License" not in joined                    # licence header
    assert "Core Directives" not in joined                   # heading inside a string


def test_mine_comments_limit(repo: Path) -> None:
    assert len(mining.mine_comments(repo, limit=2)) == 2
    assert mining.mine_comments(repo, limit=0) == []


def test_python_comment_runs_need_two_lines() -> None:
    src = "# lonely but reasonably long comment about nothing much at all here\nx = 1\n"
    assert mining._python_comment_runs(src) == []


def test_python_comment_blocks_survive_syntax_errors() -> None:
    src = "def broken(:\n# first line of a run about why this file is broken\n# second line of that same run, which should still be captured\n"
    blocks = mining._python_comment_blocks(src)
    assert any("still be captured" in text for text, _lo, _hi in blocks)


def test_comment_blocks_report_line_spans() -> None:
    src = (
        '"""Module docstring that runs across a couple of lines so the span\n'
        'is genuinely more than one line long."""\n'
        "x = 1\n"
        "# first line of a deliberate two line run\n"
        "# second line of that same run\n"
    )
    blocks = mining._python_comment_blocks(src)
    spans = {text.splitlines()[0][:12]: (lo, hi) for text, lo, hi in blocks}
    assert spans["Module docst"] == (1, 2)
    assert spans["first line o"] == (4, 5)
    for _text, lo, hi in blocks:
        assert 1 <= lo <= hi


# --------------------------------------------------------------------------
# path safety
# --------------------------------------------------------------------------


def test_safe_path_rejects_escapes_and_symlinks(repo: Path, tmp_path: Path) -> None:
    outside = tmp_path / "outside.md"
    outside.write_text("secret")
    link = repo / "link.md"
    if link.exists() or link.is_symlink():
        link.unlink()
    link.symlink_to(outside)
    try:
        assert mining._safe_path(repo, "link.md") is None
        assert mining._safe_path(repo, "../outside.md") is None
        assert mining._safe_path(repo, "/etc/hosts") is None
        assert mining._safe_path(repo, "") is None
        assert mining._safe_path(repo, "README.md") is not None
    finally:
        link.unlink()


def test_read_text_handles_binary(repo: Path, tmp_path: Path) -> None:
    blob = tmp_path / "blob.bin"
    blob.write_bytes(b"\x00\x01\x02\xff" * 100)
    assert mining._read_text(blob) == ""
    bad = tmp_path / "bad.txt"
    bad.write_bytes(b"caf\xe9 nonsense")
    assert "nonsense" in mining._read_text(bad)


# --------------------------------------------------------------------------
# pull requests
# --------------------------------------------------------------------------


def test_mine_prs_silent_without_gh(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PATH", "")
    # No gh binary anywhere: must be silent, not an exception.
    assert mining.mine_prs(repo) == []
    assert mining._gh(repo, "pr", "list") == (-1, "")


def test_mine_prs_silent_on_gh_failure(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(mining, "_gh", lambda *a, **k: (1, "gh: not authenticated"))
    assert mining.mine_prs(repo) == []
    monkeypatch.setattr(mining, "_gh", lambda *a, **k: (0, "not json at all"))
    assert mining.mine_prs(repo) == []
    monkeypatch.setattr(mining, "_gh", lambda *a, **k: (0, '{"message":"Not Found"}'))
    assert mining.mine_prs(repo) == []


def test_mine_prs_never_raises_on_timeout(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    def boom(*a: object, **k: object) -> None:
        raise subprocess.TimeoutExpired(cmd=["gh"], timeout=1)

    monkeypatch.setattr(subprocess, "run", boom)
    assert mining.mine_prs(repo) == []


def test_mine_prs_parses_bodies_and_comments(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    payload = [
        {
            "number": 7,
            "title": "Balance the sampler",
            "body": (
                "This is the change I described in the issue: the sampler now hands each\n"
                "source a share of the budget instead of a hard cap, which stops commits\n"
                "from crowding everything else out of the persona.\n\n"
                "```python\nnot_voice = True\n```\n"
            ),
            "author": {"login": "gretchenboria", "name": "Gretchen Boria"},
            "comments": [
                {
                    "author": {"login": "gretchenboria"},
                    "body": "Holding this until the doc cleaner lands, otherwise the numbers "
                            "in the budget test will move around under us again.",
                },
                {"author": {"login": "someoneelse"}, "body": "Looks good to me overall!"},
                {"author": {"login": "gretchenboria"}, "body": "lgtm"},
            ],
        }
    ]
    monkeypatch.setattr(mining, "_gh", lambda *a, **k: (0, json.dumps(payload)))
    samples = mining.mine_prs(repo, author="me@gretchenboria.com")
    assert [s.kind for s in samples] == ["pr", "pr"]
    assert samples[0].origin == "PR #7"
    assert samples[1].origin == "PR #7 comment"
    assert "not_voice" not in samples[0].text          # fence stripped
    assert "Holding this until" in samples[1].text
    joined = "\n".join(s.text for s in samples)
    assert "Looks good to me overall" not in joined    # different author
    assert "lgtm" not in joined                        # under PR_MIN_CHARS


def test_mine_prs_uses_argv_list_with_timeout(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[tuple[list[str], int]] = []
    real_run = mining._run

    def fake_run(argv: list[str], cwd: Path, timeout: int) -> tuple[int, str]:
        calls.append((argv, timeout))
        if argv[0] == "gh":
            return 0, "[]"
        return real_run(argv, cwd, timeout)

    monkeypatch.setattr(mining, "_run", fake_run)
    mining.mine_prs(repo, author="me@gretchenboria.com")
    gh_calls = [c for c in calls if c[0][0] == "gh"]
    assert gh_calls, "mine_prs should shell out to gh"
    argv, timeout = gh_calls[0]
    assert isinstance(argv, list) and argv[:3] == ["gh", "pr", "list"]
    assert isinstance(timeout, int) and 0 < timeout <= 60
    assert all(isinstance(a, str) for a in argv)


# --------------------------------------------------------------------------
# mine_all
# --------------------------------------------------------------------------


def test_mine_all_returns_multiple_kinds(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(mining, "mine_prs", lambda *a, **k: [])
    samples = mining.mine_all(repo)
    kinds = {s.kind for s in samples}
    assert {"commit", "doc", "comment"} <= kinds
    assert all(isinstance(s, Sample) for s in samples)


def test_mine_all_respects_budget(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(mining, "mine_prs", lambda *a, **k: [])
    budget = 1200
    samples = mining.mine_all(repo, budget_chars=budget)
    assert sum(len(s.text) for s in samples) <= budget
    assert samples, "budget trimming should not empty the result"


def test_mine_all_trims_longest_first(repo: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(mining, "mine_prs", lambda *a, **k: [])
    full = mining.mine_all(repo, budget_chars=10**9)
    docs_full = [s for s in full if s.kind == "doc"]
    trimmed = mining.mine_all(repo, budget_chars=900)
    docs_trimmed = [s for s in trimmed if s.kind == "doc"]
    if len(docs_trimmed) < len(docs_full) and docs_trimmed:
        longest = max(docs_full, key=lambda s: len(s.text))
        assert longest.origin not in {s.origin for s in docs_trimmed}


def test_mine_all_on_non_repo(tmp_path: Path) -> None:
    assert mining.mine_all(tmp_path) == []


def test_quotas_redistribute_unused_share() -> None:
    totals = {"commit": 100_000, "doc": 10, "comment": 10, "pr": 0}
    quotas = mining._quotas(totals, 1000)
    assert quotas["commit"] > 400, "commits should absorb the unused doc/pr share"
    assert sum(quotas.values()) <= 1000 + 4


def test_trim_to_quota_drops_longest_first() -> None:
    samples = [
        Sample(kind="doc", origin="a", text="a" * 10),
        Sample(kind="doc", origin="b", text="b" * 100),
        Sample(kind="doc", origin="c", text="c" * 20),
    ]
    kept = mining._trim_to_quota(samples, 40)
    assert [s.origin for s in kept] == ["a", "c"]
    assert mining._trim_to_quota(samples, 0) == []


# --------------------------------------------------------------------------
# read-only smoke test against this repository
# --------------------------------------------------------------------------


@pytest.mark.skipif(
    not (REPO_ROOT / ".git").exists(), reason="parent repo not a git checkout"
)
def test_smoke_against_this_repo(monkeypatch: pytest.MonkeyPatch) -> None:
    """Read-only: mine the PersonaPromptGenerator checkout without touching it."""
    monkeypatch.setattr(mining, "mine_prs", lambda *a, **k: [])
    assert mining.is_git_repo(REPO_ROOT)
    authors = mining.list_authors(REPO_ROOT)
    assert authors and authors[0][2] > 0
    samples = mining.mine_all(REPO_ROOT)
    assert samples
    assert all(s.text.strip() for s in samples)
    # Trailer stripping is a property of commit samples specifically. Docs and
    # comments may legitimately contain the word -- mining.py's own docstring
    # explains that it strips trailers, and that file is tracked.
    commits = "\n".join(s.text for s in samples if s.kind == "commit")
    assert "Co-Authored-By" not in commits
    assert "claude.ai/code" not in commits


# --------------------------------------------------------------------------
# author attribution for docs and comments (two distinct authors)
# --------------------------------------------------------------------------

ALICE = "alice@example.com"
BOB = "bob@example.com"

ALICE_DOC = """# Field notes

Alice wrote every word of this file and nobody else has ever touched it, which
makes it the cleanest possible attribution case for the blame pass to get right.
It rambles a little because that is what field notes do when nobody is editing.
"""

BOB_DOC = """# Operations runbook

Bob wrote this whole runbook on his own during an incident, and the prose is
noticeably more clipped than Alice's because he was typing it with one hand
while restarting things with the other. That contrast is the point here.
"""

SHARED_DOC_ALICE = """# Shared design doc

Alice opened this document with a long argument about why the queue should stay
single threaded, and that argument is hers alone. It goes on for a while because
she was trying to head off the obvious objection before anybody raised it.
"""

SHARED_DOC_BOB_APPENDIX = """
Bob appended this section afterwards to disagree at length, and his half of the
document reads completely differently from hers. Nobody rewrote anybody else's
lines, so blame can separate the two halves cleanly and without ambiguity.
"""

MOSTLY_BOB = """# Bob's essay

Bob wrote this entire essay by himself over a long afternoon and it is easily
long enough to clear the minimum length threshold on its own merits, several
times over, which is exactly what makes it a useful trap for the blame pass.
It keeps going for a few more sentences purely so that the whole-file version
would obviously survive if attribution were not working properly at all.
"""

ALICE_TAIL = "\nAlice fixed a typo here.\n"

SHARED_PY_ALICE = '''"""Alice wrote this module docstring and it explains at some length why the
retry logic lives here rather than in the caller, which was her decision."""


def alice_function():
    """Alice also wrote this function docstring, which argues that retrying is
    the callers problem right up until the moment that it very much is not."""
    return 1
'''

SHARED_PY_BOB = '''

def bob_function():
    """Bob wrote this docstring much later and it is about serialisation, a
    topic Alice never touched anywhere in this file or in any other file."""
    return 2


# Bob also left this two line comment run explaining that the constant below
# is deliberately odd, and Alice has never edited either of these two lines.
BOB_CONSTANT = 37
'''


@pytest.fixture(scope="module")
def two_author_repo(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A repo where Alice and Bob wrote clearly separable content."""
    root = tmp_path_factory.mktemp("twoauthor")
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "commit.gpgsign", "false")

    (root / "alice_notes.md").write_text(ALICE_DOC)
    (root / "shared_design.md").write_text(SHARED_DOC_ALICE)
    (root / "shared_module.py").write_text(SHARED_PY_ALICE)
    _commit(root, "Alice starts the design doc and the retry module here\n\n"
                  "This is the first real commit and it carries all of Alice's\n"
                  "opening material in one go for the blame test.\n",
            name="Alice Ames", email=ALICE)

    (root / "bob_runbook.md").write_text(BOB_DOC)
    (root / "bob_essay.md").write_text(MOSTLY_BOB)
    (root / "shared_design.md").write_text(SHARED_DOC_ALICE + SHARED_DOC_BOB_APPENDIX)
    (root / "shared_module.py").write_text(SHARED_PY_ALICE + SHARED_PY_BOB)
    _commit(root, "Bob adds the runbook, the essay and his half of the design\n\n"
                  "Everything in this commit is Bob's and none of it overwrites\n"
                  "a single line that Alice had already written down.\n",
            name="Bob Best", email=BOB)

    # Alice contributes three trivial lines to Bob's essay: not enough to make
    # the whole essay hers.
    (root / "bob_essay.md").write_text(MOSTLY_BOB + ALICE_TAIL)
    _commit(root, "Alice corrects one small thing in Bob's essay about queues\n\n"
                  "A three line touch that must not turn the whole essay into\n"
                  "an Alice sample when the miner attributes by author.\n",
            name="Alice Ames", email=ALICE)
    return root


def test_mine_docs_without_author_is_unchanged(two_author_repo: Path) -> None:
    origins = {s.origin for s in mining.mine_docs(two_author_repo)}
    assert {"alice_notes.md", "bob_runbook.md", "shared_design.md"} <= origins
    assert all(s.author is None for s in mining.mine_docs(two_author_repo))


def test_mine_docs_attributes_to_alice(two_author_repo: Path) -> None:
    samples = mining.mine_docs(two_author_repo, author=ALICE)
    origins = {s.origin for s in samples}
    joined = "\n".join(s.text for s in samples)
    assert "alice_notes.md" in origins
    assert "bob_runbook.md" not in origins, "Alice never touched Bob's runbook"
    assert "Alice wrote every word" in joined
    assert "Bob wrote this whole runbook" not in joined
    assert "Bob appended this section" not in joined
    assert all(s.author == ALICE for s in samples), "provenance must be recorded"


def test_mine_docs_attributes_to_bob(two_author_repo: Path) -> None:
    samples = mining.mine_docs(two_author_repo, author=BOB)
    origins = {s.origin for s in samples}
    joined = "\n".join(s.text for s in samples)
    assert "bob_runbook.md" in origins
    assert "alice_notes.md" not in origins, "Bob never touched Alice's notes"
    assert "Bob appended this section" in joined
    assert "Alice opened this document" not in joined
    assert all(s.author == BOB for s in samples)


def test_mine_docs_shared_file_splits_by_line(two_author_repo: Path) -> None:
    alice = next(
        (s for s in mining.mine_docs(two_author_repo, author=ALICE)
         if s.origin == "shared_design.md"), None
    )
    bob = next(
        (s for s in mining.mine_docs(two_author_repo, author=BOB)
         if s.origin == "shared_design.md"), None
    )
    assert alice is not None and bob is not None
    assert "single threaded" in alice.text and "disagree at length" not in alice.text
    assert "disagree at length" in bob.text and "single threaded" not in bob.text


def test_three_lines_does_not_claim_a_whole_file(two_author_repo: Path) -> None:
    """The trap: Alice's three-line touch must not yield Bob's whole essay."""
    samples = mining.mine_docs(two_author_repo, author=ALICE)
    essay = [s for s in samples if s.origin == "bob_essay.md"]
    assert essay == [], "a three line edit must not claim the whole document"
    # ...but the file is still Bob's.
    bob_origins = {s.origin for s in mining.mine_docs(two_author_repo, author=BOB)}
    assert "bob_essay.md" in bob_origins


def test_mine_comments_attributes_by_author(two_author_repo: Path) -> None:
    alice = "\n".join(s.text for s in mining.mine_comments(two_author_repo, author=ALICE))
    bob = "\n".join(s.text for s in mining.mine_comments(two_author_repo, author=BOB))
    assert "retry logic lives here" in alice
    assert "callers problem" in alice
    assert "serialisation" not in alice
    assert "deliberately odd" not in alice

    assert "serialisation" in bob
    assert "deliberately odd" in bob
    assert "retry logic lives here" not in bob


def test_mine_comments_records_provenance(two_author_repo: Path) -> None:
    samples = mining.mine_comments(two_author_repo, author=ALICE)
    assert samples
    assert all(s.author == ALICE for s in samples)
    assert all(s.author is None for s in mining.mine_comments(two_author_repo))


def test_attribution_cheap_pass_drops_untouched_files(two_author_repo: Path) -> None:
    attribution = mining._Attribution(two_author_repo, ALICE)
    assert attribution.touched("alice_notes.md") is True
    assert attribution.touched("bob_runbook.md") is False
    assert attribution.touched("shared_design.md") is True
    assert mining._Attribution(two_author_repo, None).touched("bob_runbook.md") is True


def test_attribution_degrades_when_blame_unavailable(
    two_author_repo: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """No blame budget left: keep whole files rather than raising or hanging."""
    attribution = mining._Attribution(two_author_repo, ALICE, file_cap=0)
    assert attribution.line_authors("shared_design.md") is None
    assert attribution.mask("shared_design.md", ["a", "b"]) == ["a", "b"]
    assert attribution.owns_range("shared_design.md", 1, 5, 0.9) is True

    # A blame that fails outright must behave the same way.
    monkeypatch.setattr(mining, "_git", lambda *a, **k: "")
    broken = mining._Attribution(two_author_repo, ALICE)
    assert broken.line_authors("shared_design.md") is None


def test_attribution_respects_wall_clock_budget(two_author_repo: Path) -> None:
    attribution = mining._Attribution(two_author_repo, ALICE, wall_seconds=-1.0)
    assert attribution.line_authors("shared_design.md") is None


def test_attribution_caps_blamed_files(two_author_repo: Path) -> None:
    attribution = mining._Attribution(two_author_repo, ALICE, file_cap=1)
    assert attribution.line_authors("shared_design.md") is not None
    assert attribution.line_authors("shared_module.py") is None
    assert attribution._blamed == 1


def test_mine_docs_author_finishes_promptly(two_author_repo: Path) -> None:
    import time as _time

    started = _time.monotonic()
    mining.mine_docs(two_author_repo, author=ALICE)
    assert _time.monotonic() - started < mining.BLAME_WALL_SECONDS + 10


# --------------------------------------------------------------------------
# mine_all(prs=...)
# --------------------------------------------------------------------------


def test_mine_all_prs_false_makes_no_gh_call(two_author_repo: Path,
                                             monkeypatch: pytest.MonkeyPatch) -> None:
    calls: list[list[str]] = []
    real_run = mining._run

    def watching_run(argv: list[str], cwd: Path, timeout: int) -> tuple[int, str]:
        calls.append(argv)
        return real_run(argv, cwd, timeout)

    monkeypatch.setattr(mining, "_run", watching_run)

    def explode(*a: object, **k: object) -> list[Sample]:
        raise AssertionError("mine_prs must not run when prs=False")

    monkeypatch.setattr(mining, "mine_prs", explode)
    samples = mining.mine_all(two_author_repo, prs=False)
    assert samples
    assert not any(argv and argv[0] == "gh" for argv in calls)
    assert not any(s.kind == "pr" for s in samples)


def test_mine_all_prs_true_by_default(two_author_repo: Path,
                                      monkeypatch: pytest.MonkeyPatch) -> None:
    called: list[bool] = []

    def fake_prs(*a: object, **k: object) -> list[Sample]:
        called.append(True)
        return []

    monkeypatch.setattr(mining, "mine_prs", fake_prs)
    mining.mine_all(two_author_repo)
    assert called == [True]


def test_mine_all_prs_false_redistributes_the_pr_share(
    two_author_repo: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(mining, "mine_prs", lambda *a, **k: [])
    budget = 900
    without = mining.mine_all(two_author_repo, budget_chars=budget, prs=False)
    assert sum(len(s.text) for s in without) <= budget
    # the 15% PR share is donated, not wasted
    quotas = mining._quotas(
        {"commit": 10**6, "doc": 10**6, "comment": 10**6, "pr": 0}, 1000
    )
    assert quotas["pr"] == 0
    assert sum(quotas[k] for k in ("commit", "doc", "comment")) > 950


def test_mine_all_threads_author_to_docs_and_comments(
    two_author_repo: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(mining, "mine_prs", lambda *a, **k: [])
    samples = mining.mine_all(two_author_repo, author=ALICE, prs=False)
    joined = "\n".join(s.text for s in samples)
    assert "Alice wrote every word" in joined
    assert "Bob wrote this whole runbook" not in joined
    assert "serialisation" not in joined
    for s in samples:
        if s.kind in {"doc", "comment"}:
            assert s.author == ALICE


def test_uncommitted_lines_belong_to_the_local_user(tmp_path: Path) -> None:
    """Working-tree edits are the local user's voice, not nobody's."""
    root = tmp_path / "wip"
    root.mkdir()
    _git(root, "init", "-q", "-b", "main")
    _git(root, "config", "commit.gpgsign", "false")
    _git(root, "config", "user.email", ALICE)
    _git(root, "config", "user.name", "Alice Ames")
    (root / "notes.md").write_text(BOB_DOC)
    _commit(root, "Bob writes the runbook first so the file has real history\n\n"
                  "Alice will then edit it without committing the change.\n",
            name="Bob Best", email=BOB)
    (root / "notes.md").write_text(BOB_DOC + "\n" + ALICE_DOC)

    attribution = mining._Attribution(root, ALICE)
    authors = attribution.line_authors("notes.md")
    assert authors is not None
    assert ALICE in authors, "uncommitted lines should resolve to the local user"

    samples = mining.mine_docs(root, author=ALICE)
    joined = "\n".join(s.text for s in samples)
    assert "Alice wrote every word" in joined
    assert "Bob wrote this whole runbook" not in joined
